version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: zelux-db
    environment:
      POSTGRES_USER: zelux_user
      POSTGRES_PASSWORD: zelux_password
      POSTGRES_DB: zelux_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zelux_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zelux-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    environment:
      - DATABASE_URL=postgresql://zelux_user:zelux_password@db:5432/zelux_db
      - SECRET_KEY=dev-secret-key-change-in-production
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8080"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  backend_media:

networks:
  default:
    name: zelux-network

